### ISSUE TITLE
Gibberish produced on 1 word spaces

### ISSUE THREAD

**Issue by P3GLEG** [AlexBuz/llama-zip#2]
Hey there, very cool idea. I was tinkering around and noticed that if you type 1...N chars without a space and hit enter you get gibberish. Anytime you add a space, it'll correctly compress. Probably should add a check or warning. A legitimate use case is if someone has a very long string. 

```bash
python3 llama_zip.py ../models/LLaMA3-iterative-DPO-final-GGUF/LLaMA3-iterative-DPO-final-Q2_K.gguf -i
```

```
≥≥ testing#NOSPACE
 Seamlessly announced: 36188.122745. 526. 
The tote is so much an^C

≥≥≥ testing  #SPACE HERE
HDyrKsvZ     

≥≥≥ ttt
Concatenating Levenshtein and Dynamic Programming to get to the Ground Truth.
The Levenshte^C

≥≥≥ thehomie
 Irrigation is the crucial part of farming to ensure maximum yields. Lack of uniform distribution of watering can cause uneven vegetative growth and total destruction of sensitive plant's metabolism. Examining herbaceous roots and consistent irrigation can help solve this problem.

≥≥≥ hkjdlakfjsalfkdjsalfjasdkfljalksdmckmackdlsmckalscmdkla
@include('booklayout')
@section('content')

<div class="container">
    <h2>Book List</h2>

    <ul>
        @foreach($books as $book)
            <li>
                {{ $book^C

≥≥≥ hereismylongstringidwishwouldcompresssoicandothethingiwanttodo
ESPINOZA LAW OFFICE, LLC qualifies to represent you ("us") for any type of case regarding Family Law. This webpage may oftentimes assist you, and explains some steps to recognize if you should consider hiring a lawyer.
1. Severity of the facts:


≥≥≥ hey there
WWPTluDbg        
```

**Comment by AlexBuz** [comment]
The way interactive mode works is that it tries to guess whether you want to compress or decompress based on whether the string you entered consists entirely of base64 characters. An unfortunate consequence of this, as you've discovered, is that uncompressed strings consisting entirely of base64 characters are interpreted as already compressed, which results in nonsensical output when llama-zip attempts to decompress them.

I considered requiring the user to specify somehow whether they want to compress or decompress, but in the interest of keeping interactive mode as simple to use as possible, I opted to rely on the aforementioned heuristic instead. After all, interactive mode also does not allow you to enter multiline strings, since pressing enter is how you submit.

In cases where you do need to compress such strings, I recommend using the `-c`/`--compress` mode directly, as it will compress whatever you give it without trying to determine whether it's already compressed. Alternatively, as a workaround, you can end your string with a space and interactive mode will compress it (albeit with a space at the end), but if this is acceptable then it saves you the need to exit interactive mode. If you have any alternative suggestions, I'd be love to hear them, but for now, I'm going to close this and add a note about this behavior in the README.

**Comment by P3GLEG** [comment]
No worries, makes sense and thanks for the update.
